import { NextRequest } from "next/server";
import PDFDocument from "pdfkit";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";

export const runtime = "nodejs";

const FIREFLIES_GRAPHQL = "https://api.fireflies.ai/graphql";

const GET_TRANSCRIPT_QUERY = `
  query Transcript($id: String!) {
    transcript(id: $id) {
      id
      title
      date
      sentences {
        speaker_name
        text
      }
    }
  }
`;

async function fetchTranscript(id: string) {
  const apiKey = process.env.FIREFLIES_API_KEY;
  if (!apiKey) throw new Error("FIREFLIES_API_KEY not configured");

  const res = await fetch(FIREFLIES_GRAPHQL, {
    method: "POST",
    headers: {
      Authorization: "Bearer " + apiKey,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ query: GET_TRANSCRIPT_QUERY, variables: { id } }),
  });

  if (!res.ok) throw new Error("Fireflies API error (" + res.status + ")");
  const data = await res.json();
  if (data.errors) throw new Error(data.errors[0]?.message || "GraphQL error");
  if (!data.data?.transcript) throw new Error("Transcript not found");

  const t = data.data.transcript;
  const sentences: { speaker_name: string; text: string }[] = t.sentences || [];

  // Build speaker blocks
  const blocks: { speaker: string; lines: string[] }[] = [];
  let currentSpeaker = "";
  for (const s of sentences) {
    if (s.speaker_name !== currentSpeaker) {
      currentSpeaker = s.speaker_name;
      blocks.push({ speaker: s.speaker_name, lines: [] });
    }
    blocks[blocks.length - 1].lines.push(s.text);
  }

  return {
    title: t.title || "Untitled Meeting",
    date: t.date ? new Date(Number(t.date)).toLocaleDateString("en-US", {
      weekday: "long", year: "numeric", month: "long", day: "numeric",
    }) : "Unknown date",
    blocks,
  };
}

function sanitize(text: string): string {
  return text.replace(/[<>:"/\\|?*]/g, "_").substring(0, 100);
}

async function generatePDF(title: string, date: string, blocks: { speaker: string; lines: string[] }[]): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Title
    doc.fontSize(18).font("Helvetica-Bold").fillColor("#0a0e17")
      .text(title, { align: "center" });
    doc.moveDown(0.3);

    // Date
    doc.fontSize(10).font("Helvetica").fillColor("#64748b")
      .text(date, { align: "center" });
    doc.moveDown(0.5);

    // Divider
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#e2e8f0").lineWidth(0.5).stroke();
    doc.moveDown(0.8);

    // Transcript
    for (const block of blocks) {
      // Speaker name
      doc.fontSize(10).font("Helvetica-Bold").fillColor("#06b6d4")
        .text(block.speaker + ":", { continued: false });
      doc.moveDown(0.2);

      // Speaker text
      const text = block.lines.join(" ");
      doc.fontSize(9.5).font("Helvetica").fillColor("#1e293b")
        .text(text, { align: "left", lineGap: 3 });
      doc.moveDown(0.6);
    }

    // Footer
    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#e2e8f0").lineWidth(0.5).stroke();
    doc.moveDown(0.4);
    doc.fontSize(7).font("Helvetica").fillColor("#94a3b8")
      .text("Generated by FireFlies Email Tool", { align: "center" });

    doc.end();
  });
}

async function generateDOCX(title: string, date: string, blocks: { speaker: string; lines: string[] }[]): Promise<Buffer> {
  const children: Paragraph[] = [];

  // Title
  children.push(new Paragraph({
    heading: HeadingLevel.HEADING_1,
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: title, bold: true, size: 32, color: "0a0e17" })],
    spacing: { after: 100 },
  }));

  // Date
  children.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: date, size: 20, color: "64748b" })],
    spacing: { after: 300 },
  }));

  // Transcript blocks
  for (const block of blocks) {
    // Speaker
    children.push(new Paragraph({
      children: [new TextRun({ text: block.speaker + ":", bold: true, size: 21, color: "06b6d4" })],
      spacing: { before: 200, after: 60 },
    }));

    // Text
    children.push(new Paragraph({
      children: [new TextRun({ text: block.lines.join(" "), size: 20, color: "1e293b" })],
      spacing: { after: 120 },
    }));
  }

  // Footer
  children.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: "Generated by FireFlies Email Tool", size: 14, color: "94a3b8", italics: true })],
    spacing: { before: 400 },
  }));

  const doc = new Document({
    sections: [{ children }],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const format = request.nextUrl.searchParams.get("format") || "pdf";

    if (!["pdf", "docx"].includes(format)) {
      return Response.json({ error: "Format must be pdf or docx" }, { status: 400 });
    }

    const { title, date, blocks } = await fetchTranscript(id);
    const fileName = sanitize(title);

    if (format === "pdf") {
      const buffer = await generatePDF(title, date, blocks);
      return new Response(new Uint8Array(buffer), {
        headers: {
          "Content-Type": "application/pdf",
          "Content-Disposition": `attachment; filename="${fileName}.pdf"`,
        },
      });
    } else {
      const buffer = await generateDOCX(title, date, blocks);
      return new Response(new Uint8Array(buffer), {
        headers: {
          "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          "Content-Disposition": `attachment; filename="${fileName}.docx"`,
        },
      });
    }
  } catch (error: any) {
    console.error("Download error:", error);
    return Response.json({ error: error.message || "Failed to download" }, { status: 500 });
  }
}
